<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import type { SearchPlan } from '@/types'
import { searchApi } from '@/composables/useApi'
import { useSessionStore } from '@/stores/session'
import GlassCard from '@/components/common/GlassCard.vue'

const sessionStore = useSessionStore()
const plans = ref<SearchPlan[]>([])
const loading = ref(false)
const expandedId = ref<number | null>(null)

async function loadPlans() {
  if (!sessionStore.currentSession) return
  loading.value = true
  try {
    plans.value = await searchApi.listPlans(sessionStore.currentSession.id)
  } finally {
    loading.value = false
  }
}

async function handleAction(planId: number, action: 'approve' | 'reject') {
  const updated = await searchApi.planAction(planId, action)
  const idx = plans.value.findIndex(p => p.id === planId)
  if (idx !== -1) plans.value[idx] = updated
}

function toggle(id: number) {
  expandedId.value = expandedId.value === id ? null : id
}

const statusBadge: Record<string, string> = {
  draft: 'badge-warning',
  approved: 'badge-success',
  executing: 'badge-info',
  completed: 'badge-success',
  failed: 'badge-error',
  rejected: 'badge-error',
}

watch(() => sessionStore.currentSessionId, loadPlans)
onMounted(loadPlans)
</script>

<template>
  <div>
    <h1 class="text-xl font-semibold text-[var(--text-primary)] mb-1">Search Plans</h1>
    <p class="text-sm text-[var(--text-secondary)] mb-6">
      Review and approve search strategies generated by the AI.
    </p>

    <div v-if="!sessionStore.currentSession" class="text-[var(--text-muted)]">
      Select a session first.
    </div>

    <div v-else-if="loading" class="text-[var(--text-muted)]">Loading plans...</div>

    <div v-else-if="plans.length === 0" class="text-[var(--text-muted)]">
      No search plans yet. Ask the AI to create one in Chat.
    </div>

    <div v-else class="space-y-4">
      <GlassCard v-for="plan in plans" :key="plan.id">
        <!-- Header row -->
        <div
          class="flex items-center justify-between cursor-pointer"
          @click="toggle(plan.id)"
        >
          <div>
            <span class="font-medium text-[var(--text-primary)]">
              {{ plan.plan_data.topic }}
            </span>
            <span :class="['badge ml-3', statusBadge[plan.status]]">
              {{ plan.status }}
            </span>
          </div>
          <span class="text-[var(--text-muted)] text-xs">
            {{ new Date(plan.created_at).toLocaleDateString() }}
          </span>
        </div>

        <!-- Expanded detail -->
        <div v-if="expandedId === plan.id" class="mt-4 space-y-3 text-sm">
          <p class="text-[var(--text-secondary)]">{{ plan.plan_data.description }}</p>

          <!-- Year range -->
          <div v-if="plan.plan_data.year_range.from || plan.plan_data.year_range.to">
            <span class="text-[var(--text-muted)]">Year range:</span>
            {{ plan.plan_data.year_range.from ?? '...' }} - {{ plan.plan_data.year_range.to ?? '...' }}
          </div>

          <!-- Queries -->
          <div>
            <h4 class="text-[var(--text-muted)] mb-2">Queries ({{ plan.plan_data.queries.length }})</h4>
            <div
              v-for="(q, i) in plan.plan_data.queries"
              :key="i"
              class="glass-card p-3 mb-2"
            >
              <div class="font-mono text-xs text-[var(--accent-primary)]">{{ q.source }}</div>
              <div class="text-[var(--text-primary)] mt-1">{{ q.query }}</div>
              <div class="text-[var(--text-muted)] text-xs mt-1">{{ q.rationale }}</div>
            </div>
          </div>

          <!-- Inclusion / Exclusion -->
          <div v-if="plan.plan_data.inclusion_criteria.length" class="text-[var(--text-secondary)]">
            <span class="text-[var(--text-muted)]">Include:</span>
            {{ plan.plan_data.inclusion_criteria.join('; ') }}
          </div>
          <div v-if="plan.plan_data.exclusion_criteria.length" class="text-[var(--text-secondary)]">
            <span class="text-[var(--text-muted)]">Exclude:</span>
            {{ plan.plan_data.exclusion_criteria.join('; ') }}
          </div>

          <!-- Actions -->
          <div v-if="plan.status === 'draft'" class="flex gap-3 pt-2">
            <button
              class="glass-btn glass-btn-primary"
              @click.stop="handleAction(plan.id, 'approve')"
            >
              Approve
            </button>
            <button
              class="glass-btn"
              @click.stop="handleAction(plan.id, 'reject')"
            >
              Reject
            </button>
          </div>
        </div>
      </GlassCard>
    </div>
  </div>
</template>
